version: 2
jobs:
  build:
    working_directory: ~/opt/self-service/
    docker:
      - image: circleci/python:3.8.3
        environment:
          PIPENV_VENV_IN_PROJECT: true
      - image: mockserver/mockserver
        name: mockserver.mockserver
    steps:
      - checkout # check out source code to working directory
      - run:
          command: |
            sudo chown -R circleci:circleci /usr/local/bin
            sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages
      - run:
          command: |
            cp .circleci/user_variables.py framework/user_variables.py
            pip install pipenv
            pipenv install --dev
      - run:
          command: |
            pipenv run python -m unittest tests/test_host_groups.py
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
